### ISSUE TITLE
I, uh...don't have an ORM

### ISSUE THREAD

**Issue by Goorzhel** [Goorzhel/good#3]
In the three months that I spent on this project, it's a sizable blow to my ego that I never once registered the absolute lunacy of hand-implementing object-relational mapping. Thanks, @agargiulo, for catching that.

TODO: investigate [GORM](https://gorm.io/). (I'm not the only one getting a weird _Galidor_ vibe from that name, am I?)

**Comment by agargiulo** [comment]
To be fair, you don't necessarily need an ORM but it'd be better to have something besides raw `db.Exec` queries.

**Comment by Goorzhel** [comment]
Bah—I didn't think through my word choice there.

**Comment by Goorzhel** [comment]
[No point](https://eli.thegreenplace.net/2019/to-orm-or-not-to-orm/) beating my head on this any further.
